### ISSUE TITLE
🏷️ Create develop branch

### ISSUE THREAD

**Issue by lucianobragaweb** [facedigital/crudify#10]
### Is your proposal related to a problem?

No, only a suggestion to make this repo more organized and define a git flow pattern.

### Describe the solution you'd like

Create a develop branch and protect the main branch. In this case, all the pull requests from the contributors can be merged in develop. With this can we create new realease based on develop before the merge in main branch.

### Describe alternatives you've considered

Can be deliberate about this or other solutions in this thread.

**Comment by rosseti** [comment]
Branch "develop" created and "main" protected. Thank you!
